version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    # entrypoint: node
    command: npm start
    environment:
      - FB_ID=$FB_ID
      - FB_SECRET=$FB_SECRET
      - PORT=80
      - DEBUG=0
  postgres:
    image: postgres
